### ISSUE TITLE
Code gets stuck with multiple GPUs

### ISSUE THREAD

**Issue by JayParanjape** [lengmo1996/ECDM#6]
When I tried running the scripts as they are, I am facing an issue where the program gets stuck at this stage:
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 8 processes
----------------------------------------------------------------------------------------------------

Missing logger folder: logs/2024-11-27T22-21-01_ecdm_first_stage/tensorboard
Missing logger folder: logs/2024-11-27T22-20-46_ecdm_first_stage/tensorboard
Missing logger folder: logs/2024-11-27T22-21-01_ecdm_first_stage/tensorboard
Missing logger folder: logs/2024-11-27T22-21-01_ecdm_first_stage/tensorboard
Missing logger folder: logs/2024-11-27T22-21-01_ecdm_first_stage/tensorboard
Missing logger folder: logs/2024-11-27T22-21-01_ecdm_first_stage/tensorboard
Missing logger folder: logs/2024-11-27T22-21-01_ecdm_first_stage/tensorboard

After this, the training does not start, and the process is stuck endlessly, which I believe is due to some issue with the parallel computing. The same happened with 2 and 4 GPUs. The process works when I run this on a single GPU. Can you please help me debug as to what is going wrong?
Thanks

**Comment by lengmo1996** [comment]
You could try to set the environment variable: NCCL_P2P_DISABLE=1.

**Comment by JayParanjape** [comment]
Thanks, that did the trick

**Comment by JayParanjape** [comment]
Also, getting this error after the first epoch: lightning.fabric.utilities.exceptions.MisconfigurationException: `ModelCheckpoint(monitor='val/loss_simple_ema')` could not find the monitored key in the returned metrics: ['train/loss', 'train/loss_step', 'global_step', 'lr_abs', 'val/loss', 'val/loss_ema', 'train/loss_epoch', 'epoch', 'step']. HINT: Did you call `log('val/loss_simple_ema', value)` in the `LightningModule`?

**Comment by lengmo1996** [comment]
I'm sorry. This error may have been caused by me not doing a global check after updating some codes. You can change the “loss_simple_ema” in the config to “loss_ema.”

**Comment by JayParanjape** [comment]
Yeah, I thought so.. I changed it to loss_ema and it is working. Thanks for your quick responses. Closing this issue
